name: rohitpipeline
on: push
jobs:
  checklinting:
    name: linkcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Super-Linter
        uses: github/super-linter@v4.9.7
